name = input("Enter your name: ")
current_role = input("Enter your current role: ")
target_role = input("Enter your target role: ")
years_of_experience = int(input("Enter your years of experience: "))
current_skills = input("Enter your current skills (comma-separated): ").split(",")
target_skills = input("Enter your target skills (comma-separated): ").split(",")
print("\n=====================\n")
print("Career Profile")
print("\n=====================\n")
print(f"Name: {name}")
print(f"Current Role: {current_role}")
print(f"Target Role: {target_role}")
print(f"Years of Experience: {years_of_experience}")
print(f"Current Skills: {', '.join(current_skills)}")
print(f"Target Skills: {', '.join(target_skills)}")
